manifest: 
  
  defaults:
      remote: xmos

  remotes:
    - name: xmos
      url-base: git@github.com:xmos 

  projects: 
    - name: sw_usb_audio
      repo-path: sw_usb_audio
      revision: develop
    
    - name: lib_xua
      repo-path: lib_xua
      revision: develop

